// Code generated by "stringer -type=DataType"; DO NOT EDIT.

package mpi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Byte-0]
	_ = x[Uint-1]
	_ = x[Int-2]
	_ = x[Ulong-3]
	_ = x[Long-4]
	_ = x[Float-5]
	_ = x[Double-6]
	_ = x[Complex-7]
}

const _DataType_name = "ByteUintIntUlongLongFloatDoubleComplex"

var _DataType_index = [...]uint8{0, 4, 8, 11, 16, 20, 25, 31, 38}

func (i DataType) String() string {
	if i >= DataType(len(_DataType_index)-1) {
		return "DataType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataType_name[_DataType_index[i]:_DataType_index[i+1]]
}
