// Code generated by "stringer -type=Op"; DO NOT EDIT.

package mpi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpSum-0]
	_ = x[OpMin-1]
	_ = x[OpMax-2]
	_ = x[OpProd-3]
	_ = x[OpLand-4]
	_ = x[OpLor-5]
	_ = x[OpLxor-6]
	_ = x[OpBand-7]
	_ = x[OpBor-8]
	_ = x[OpBxor-9]
}

const _Op_name = "OpSumOpMinOpMaxOpProdOpLandOpLorOpLxorOpBandOpBorOpBxor"

var _Op_index = [...]uint8{0, 5, 10, 15, 21, 27, 32, 38, 44, 49, 55}

func (i Op) String() string {
	if i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
