// Copyright 2016 The Gosl Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// *** NOTE: this file was auto generated by all.bash ***
// ***       and should be ignored                    ***

// +build !windows

package mpi

/*
#cgo CFLAGS: -I/usr/lib/arm-linux-gnueabihf/openmpi/include/openmpi -I/usr/lib/arm-linux-gnueabihf/openmpi/include -pthread
#cgo LDFLAGS: -pthread -L/usr/lib/arm-linux-gnueabihf/openmpi/lib -lmpi
*/
import "C"
