on: [push, pull_request]
name: Test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Stable Go for Bootstrap
      uses: actions/setup-go@v6
      with:
        go-version: 'stable'

    - name: Download Go Tip
      run: |
        go install golang.org/dl/gotip@latest
        gotip download
        echo "$HOME/sdk/gotip/bin" >> $GITHUB_PATH

    - name: Install OpenMPI
      run: sudo apt update && sudo apt install -y --no-install-recommends openmpi-bin libopenmpi-dev

    - name: Build
      run: go build ./...

    - name: Test
      run: mpirun -n 4 --oversubscribe go test .
